Fix compilation error in gcc by returning bool_proxy as value instead of reference to temporary
The error was:

../vector/kth_cprog_vektor_bool.cpp: In member function ‘Vector<bool>::bool_proxy& Vector<bool>::const_iterator::operator[](size_t)’:
../vector/kth_cprog_vektor_bool.cpp:146:37: error: invalid initialization of non-const reference of type ‘Vector<bool>::bool_proxy&’ from an rvalue of type ‘Vector<bool>::bool_proxy’
     return bool_proxy(element, index);
                                          ^